### PR TITLE
Made DB a class and improved some mechanics

### PR DESCRIPTION
**Pull request by f-doot**

### CODE REVIEW

**Review by lexwebb — APPROVED** [review]
+1 for JSDocs and fancifying of promises

**Comment by sdf010** [comment]
I think we should have a fixed way of handling 'services' where each service called with config,auth and a link to app.js (so services can call back to other services). I think @NotARealTree has started this but it can be adapted so it is generic.

**Comment by f-doot** [comment]
I don't think we're going to be able to make some sort of default service
interface type etc, feels like we'd be shoehorning js. We could enforce
that as a standard but for now I think we should just do what works

**Comment by sdf010** [comment]
The 'service' does not have to make a use of all the parameters we pass to it. its just that each service seems to require either auth, config or access to other services. this should also help with having a singleton services.

**Pull request merged**
